#!/bin/sh

cat $1                      |
sed '/^#!\/bin\/*sh$/d'     |
sed '/^$/d'                 |
sed 's/ | / |\n/g'          |
sed '1i#!/bin/sh\n'         |
tac                         |
awk '/<[(][^<]*[)]/{bash++} /^#!\/bin\/bash$/{next} {if(bash != 0){sub(/^#!\/bin\/sh$/, "#!/bin/bash", $0)}; print}' |
tac                         |
python2 /home/TOOL/sb_pipealign
