#!/bin/sh

#
# Abstract
#   Arch Linuxの更新パッケージ(除Testing)を通知するbotスクリプト
#   (https://twitter.com/arch_update_bot)
#
# Require
# - tac(GNU textutils)
# - t(ruby gem "https://github.com/sferik/t")
#

#set -evx

#
# nohup
#



file_path='/tmp'
#trc_file='/home/gin/.trc_update_bot'


if [ -s $file_path/arch_pkg_list.txt ]; then
    mv $file_path/arch_pkg_list.txt $file_path/arch_pkg_list_old.txt
fi


curl --fail --silent https://www.archlinux.org/feeds/packages/ \
|
gawk 'END {print}' \
|
sed -e 's;<item>;\n&;g' \
|
sed -e 's;</item>;&\n;g' \
|
grep -Ev '(community|multilib)?-?testing' \
|
grep -v '^$' \
|
grep -v '<rss ' \
|
grep -v '</rss>' \
|
sed -e 's;</\?item>;;g' \
|
sed -e 's;<[^/]*>;;g' \
|
sed -e 's;</[[:alnum:]_-]*>;%;g' \
|
gawk -F% '{OFS="#"; print $1$6,"\""$3"\"",$5}' \
|
sed -e 's@tag:www.archlinux.org,@@' \
|
sed -e 's@:/packages/.*@@' \
|
sed -e 's;\(x86_64\|i686\|any\);(&/;' \
|
sed -e 's;#";)&;' \
|
sed -e 's/\&amp;/\&/g' -e 's/\&lt;/</g' -e 's/\&gt;/>/g' -e 's/\&nbsp;/ /g' \
|
tr -d '"' > $file_path/arch_pkg_list.txt


if [ ! "-s $file_path/arch_pkg_list.txt" ]; then
    mv $file_path/arch_pkg_list_old.txt $file_path/arch_pkg_list.txt
fi

if [ ! -e $file_path/arch_pkg_list.txt ]; then
    exit
elif [ ! -e $file_path/arch_pkg_list_old.txt ]; then
    exit
fi



cmp -s $file_path/arch_pkg_list.txt $file_path/arch_pkg_list_old.txt || diff $file_path/arch_pkg_list.txt $file_path/arch_pkg_list_old.txt \
|
tac \
|
grep -E '^< ' \
|
sed -e 's/^<//g' \
|
gawk -F# 'NF == 3 {OFS="#"; print $1,gensub("'\''", "'\''\\\\'\'''\''", "g", $2), $3}' \
| #t updateで引数を適切に扱えるように、シングルクォートを加工 ### 140字以下に切り詰められた際、クォートの対応が取れなくなる可能性がある。
gawk -F# '{OFS="#"; print $1,gensub("(https?):(//)", "\\1;\\2", "g", $2), $3}' \
| #post時にURL展開をされないように、https?://を加工
gawk -F# '{OFS="#"; print $1,gensub("\\.(net|NET|org|Org|com|at|tv|info|gov|edu|coop|asia|biz|int|mobi)", " dot \\1", "g", $2), $3}' \
| #post時にURL変換されないように、TLDを加工
gawk -F# '\
    BEGIN {OFS="#"; max_chars=135}; \
    length($0) > max_chars {printf("%s#\"%s...\"#<%s>\n",$1, substr($2,1,(max_chars - (length($1)+length($3)+3))), $3); next}; \
    {print $1,"\""$2"\"","<"$3">"}' \
|
sed -e 's@^ @t update -P /home/gin/.trc_update_bot '\''@' \
|
sed -e 's@$@'\''; sleep 20;@' \
|
tr '#' '\n' \
|
tee ~/tmp/arch_update_info_notifier_testlog.txt \
|
sh 1> /dev/null
