#!/bin/bash

#set -exv

pkg_ver=$(date '+%Y%m%d')

ERROR_CHECK() {
    [ $(echo ${PIPESTATUS[@]} | awk '{for(i=1;i<=NF;i++){s+=$i}} END{print s}') -eq 0 ] && return
    [ -e /tmp/man-pages-ja-${pkg_ver}.md5 ] && rm /tmp/man-pages-ja-${pkg_ver}.md5
    exit 1
}


curl -s https://linuxjm.osdn.jp/download.html     |
grep "man-pages-ja-${pkg_ver}.tar.gz" >/dev/null
ERROR_CHECK

[ -e /tmp/man-pages-ja-${pkg_ver}.md5 ] && exit 2

curl -s https://linuxjm.osdn.jp/man-pages-ja-${pkg_ver}.tar.gz     |
md5sum                                                             |
awk '$0=$1' > /tmp/man-pages-ja-${pkg_ver}.md5
ERROR_CHECK

t update -P /home/gin/.trc "@gin_135 man-pages-ja(${pkg_ver}版)がリリースされているぞい。
https://linuxjm.osdn.jp/man-pages-ja-${pkg_ver}.tar.gz
MD5: $(cat /tmp/man-pages-ja-${pkg_ver}.md5)" >/dev/null
