#!/bin/sh

find $1 -type f -name 'Thumbs.db' -o -name 'desktop.ini'     | # Thumbs.dbおよびdesktop.iniのパスの出力
sed 's/.*/"&"/'                                              | # パスのクォーティング(スペース含パス対策)
xargs -I@ rm -v @                                              # 削除の実行
