#!/bin/sh

#
# Usage: $ get_jp_ipv4
#


curl --fail --silent http://ftp.apnic.net/stats/apnic/delegated-apnic-latest |
grep "JP" |
grep "ipv4" |
awk -F'|' '{OFS=""; print $4,"/",log(2**32/$5)/log(2)}'
