#!/bin/bash
#
# get_jreast_status JR東日本の電車運行状況を取得する
#
# usage: get_jrkanto_status [AREA]
# [AREA]: kanto(default), tohoku, shinetsu, shinkansen
#
# written by Tatsunori Aoki (ginjiro.135 at gmail.com) / Date: 2017-04-07
#
# 新幹線って、エリアなのか...??

# set -xv

# エラーチェック用関数
ERROR_CHECK() {
    #[ $(plus ${PIPESTATUS[@]}) -eq 0 ] && return
    [ $(echo ${PIPESTATUS[@]} |awk '{for(i=1;i<=NF;i++){s+=$i}} END{print s}') -eq 0 ] && return
    exit 1
}


curl -s http://traininfo.jreast.co.jp/train_info/${1:-"kanto"}.aspx   | # ソースの取得
nkf -Lu                                                               | # 改行コードの変換
grep -A 1 'text-tit-xlarge'                                           | # 路線名、運行状況レコードの抽出
sed '/acess_i/s/.*alt="\([^"]*\)".*/\1/'                              | # 運行状況レコードの整形
sed 's/<[^>]*>//g'                                                    | # HTMLタグの除去
tr -d -- '- '                                                         | # 不要文字の除去
awk NF=NF                                                             | # 空行の除去
xargs -n 2                                                              # 出力の整形

ERROR_CHECK

exit 0
