#!/bin/sh
#
# passgen パスワード用のランダムな文字列を生成する
#
# usage: passgen [length] [class]
# [length]: (default: 32)
# [class]: alnum, alpha, digit, print
#
# written by Tatsunori Aoki (ginjiro.135 at gmail.com) / Date: 2017-10-24

cat /dev/random              | # 文字ソースの出力
tr -dc "[:${2:-alnum}:]"     | # 指定された文字クラスの抽出
fold -w ${1:-32}             | # 指定された文字数の抽出
head -n 1                      # パスワードの出力
