#!/bin/bash
#
# pc2addr 郵便番号を住所に変換する
#
# usage: pc2addr <POSTAL_CODE>
#
# written by Tatsunori Aoki (ginjiro.135@gmail.com) / Date: 2016-10-14


# エラーチェック用関数
ERROR_CHECK() {
    # [ $(plus ${PIPESTATUS[@]}) -eq 0 ] || exit 2
    [ $(echo ${PIPESTATUS[@]} |awk '{for(i=1;i<=NF;i++){s+=$i}} END{print s}') -eq 0 ] && return
    exit 2
}

# 引数数のチェック
[ $# -eq 1 ] || exit 1

echo $1                                                                 | # 郵便番号の出力
tr -d '-'                                                               | # ハイフンの除去
xargs -I@ curl --fail --silent 'http://zip.cgis.biz/csv/zip.php?zn='@   | # 住所の取得
nkf -w -Lu                                                              | # 文字・改行コードの変換
awk '{r[NR]=$0} END{if(NR<2){exit 1}; for(i=1;i<=NR;i++){print r[i]}}'  | # エラーチェック
tr -d '"'                                                               | # ダブルクォートの除去
awk -F, 'NR==2{print $5$6$7}'                                             # レコード・フィールドの抽出

ERROR_CHECK

exit 0
