#!/bin/sh
#
# print_oreilly_animals O'reillyの書籍カバーに描かれている動物の全リストを出力する
#
# usage: print_oreilly_animals
#
# written by Tatsunori Aoki (ginjiro.135 at gmail.com) / Date: 2022-04-26

curl -s https://www.oreilly.com/animals.csp                            | # ソースの取得
grep 'class="pagination pagination--top"'                              | # 最大レコード数の取得1
grep -o 'of [0-9]*'                                                    | # 最大レコード数の取得2
cut -d ' ' -f 2                                                        | # 最大レコード数の取得3
sed 's#.*#curl -s https://www.oreilly.com/animals.csp?x-o="[0-&:20]"#' | # curlコマンドの生成
sh                                                                     | # コマンドの実行
nkf -w                                                                 | # 文字コードの変換
grep 'class="animal-name"'                                             | # 動物名の抽出
sed 's/<[^<]*>//g'                                                     | # HTMLタグの除去
sed 's/^\s*//'                                                         | # 行頭の余分なスペースの除去
sort                                                                   | # ソート
uniq                                                                     # 重複レコードの除去
