#!/bin/sh
#
# up カレントディレクトリパスから、指定した数だけ上の階層の絶対パスを表示する。
#
# usage: cd $(up num)    # cdとコマンド置換を組み合わせて使う
#
# written by Tatsunori Aoki (ginjiro.135 at gmail.com)

pwd                                                     |
awk -F/ '{print NF,$0}'                                 |
awk -v"n=${1:-0}" '$1<=n{print $2} n<$1{print $1-n,$2}' |
awk 'NF==1; NF==2{split($2,pass,"/"); for(i=1;i<=$1;i++){printf pass[i]"/"}; print ""}'
